#! /bin/sh

set -e

#---------------------------------------------------------------------
#                            pre-remove
# 
# Executed before the package is removed.
#
# http://code.google.com/p/fwtemplates/wiki/PackageHooks
#---------------------------------------------------------------------

case "$1" in
  upgrade)
    # defer to newer package's script
    exit 1
    ;;
  failed-upgrade)
    # actually handle the upgrade here
    # old-version is $2
    ;;
  remove)
    ;;
  *)
    ;;
esac

exit 0
